### ISSUE TITLE
Failed to resolve component

### ISSUE THREAD

**Issue by VedantParanjape** [chegewara/esp32s2-usb-host-example#4]
On running `idf.py set-target esp32s2`, this command fails with the following error

```bash
CMake Error at /home/vedant/esp/esp-idf/tools/cmake/build.cmake:186 (message):
  Failed to resolve component 'hal'.
```

**Comment by chegewara** [comment]
Which esp-idf version are you running on?

**Comment by VedantParanjape** [comment]
`ESP-IDF v4.2`

**Comment by chegewara** [comment]
This esp-idf does not support host. It is running in master/v4.4+.

**Comment by VedantParanjape** [comment]
Ok, I'll close this issue then.
