### ISSUE TITLE
XFER ERROR 1

### ISSUE THREAD

**Issue by bembite** [chegewara/esp32s2-usb-host-example#5]
Compiled and flashed your example. I also connected USB flash drive(tried 2 different) to my board. I recieving such output:

```
Hello world USB host!
I (325) : USB host setup properly
I (325) : Port is power ON now
I (335) : port event: 1
start pipe event task
I (585) : HCD_PORT_EVENT_CONNECTION
I (585) : HCD_PORT_STATE_DISABLED
I (645) : USB device reset
I (645) : HCD_PORT_STATE_ENABLED
W (645) ERROR: 80 06 00 01 00 00 12 00 
W (645) : XFER error: 1
```
How can I test usb host in another way? Thank you!

**Comment by chegewara** [comment]
Sorry for delay, but i have no time to check it.
I think you are trying to get string from device, but there is no string you are trying to request.

**Comment by bembite** [comment]
> I think you are trying to get string from device, but there is no string you are trying to request.

Thank you for your response.
Do yo mean [msg.pipe_event](https://github.com/chegewara/esp32s2-usb-host-example/blob/74d8cae11f55ebd888cf924d5d00cd95278babfa/main/main.c#L111)? As I understand error appears after starting ctrl_pipe_event_task and recieving first msg. Still looking how to solve this...

**Comment by chegewara** [comment]
Sorry, i was wrong about command.
Try to add small delay before this line:
https://github.com/chegewara/esp32s2-usb-host-example/blob/74d8cae11f55ebd888cf924d5d00cd95278babfa/main/main.c#L177

**Comment by bembite** [comment]
Sorry, my bad! I had bad connection to GPIO19. After resoldering it works fine with your original code!

**Comment by chegewara** [comment]
No problem, im glad it is working for you.
